export const address = [
    {city:'Aguai', address:'R. Carlos Gomes, 397 Centro - Aguai, SP'},
    {city:'Alfenas', address:'R. João Pinheiro, 116 Centro - Alfenas, MG'},
    {city:'Alterosa', address:'R. Mal Deodoro da Fonseca, 114 Centro - Alterosa, MG'},
    {city:'Andira', address:'R. São Paulo, 900 Centro - Andira, PR'},
    {city:'Araras', address:'R. Benedita Nogueira, 631 Centro - Araras, SP'},
    {city:'Areado', address:'R. Prof. César Filho, 33 Centro - Areado, MG'},
    {city:'Assis', address:'R. Quintino Bocaiuva, 132 Centro  - Assis, SP'},
    {city:'Atibaia', address:'R. José Pires, 65 Centro - Atibaia, SP'},
    {city:'Bandeirantes', address:'R. Dr Benedito Bernardes de Oliveira, 158 Centro - Bandeirantes, PR'},
    {city:'Bastos', address:'R. Adhemar de Barros, 433 Centro - Bastos, SP'},
    {city:'Bernardino de Campos', address:'R. Mato Grosso, 96 Centro - Bernardino de Campos, SP'},
    {city:'Botelhos', address:'Av. Maj. Antônio A Fernandes, 226 Centro - Botelhos, MG'},
    {city:'Brejinho', address:'Av. Antônio Alves Pessoa, 1661 Brejinho - Brejinho, RN'},
    {city:'Caconde', address:'R. Duque de Caxias, 347 Centro - Caconde, SP'},
    {city:'Caldas', address:'Pç. Paulino Figueiredo, 165 Caldas - Caldas, MG'},
    {city:'Cambará', address:'R. Dr. Genaro Resende, 1040 Centro - Cambará, PR'},
    {city:'Campos Novos Paulista', address:'Av. José Theodoro de Souza, 435 Centro - Campos Novos Paulista, SP'},
    {city:'Cândido Mota', address:'R. Henrique Vasques, 504 Centro  - Cândido Mota, SP'},
    {city:'Canguaretama', address:'R. Doutor Pedro Velho, 19 Sala 11Centro - Canguaretama, RN'},
    {city:'Carlópolis', address:'R. Benedito Sales, 858B Centro - Carlópolis, PR'},
    {city:'Casa Branca', address:'R. Coronel José Julho, 571 Centro - Casa Branca, SP'},
    {city:'Chavantes', address:'R. Coronel Júlio Silva, 339 Centro - Chavantes, SP'},
    {city:'Cornélio Procópio', address:'R. Massud Amim, 254 Centro - Cornélio Procópio, PR'},
    {city:'Divisa Nova', address:'Pç. Governador Valadares 23 Centro - Divisa Nova, MG'},
    {city:'Elói Mendes', address:'R. Sete de Setembro, 134Centro - Elói Mendes, MG'},
    {city:'Espírito Santo do Pinhal', address:'R. Abelardo César, 159 Centro - Espírito Santo do Pinhal, SP'},
    {city:'Eunápolis', address:'Av. Rui Barbosa, 507 Centro - Eunápolis, BA'},
    {city:'Fartura', address:'Pç. Manoel Remígio Viana, 146 Centro  - Fartura, SP'},
    {city:'Fortaleza', address:'R. Vicente Leite, 2266 Dionísio Torres - Fortaleza, CE'},
    {city:'Goianinha', address:'R.: Coronel Manoel Duarte, 96 Centro - Goianinha, RN'},
    {city:'Guaxupé', address:'Av. Dona Floriana, 1130 Jardim Três Rosas - Guaxupé, MG'},
    {city:'Ibirarema', address:'R. Francisco Pontremolez, 314 Centro  - Ibirarema, SP'},
    {city:'Ipaussu', address:'R. Cristiano Rodrigues da Silva, 684 Centro - Ipaussu, SP'},
    {city:'Ipuiuna', address:'R. São Benedito, 110 Centro - Ipuiuna, MG'},
    {city:'Itaberá', address:'R. Coronel José Pedro de Lima, 253 Centro - Itaberá, SP'},
    {city:'Itajuba', address:'R. Francisco Pereira, 39, loja 2 Varginha - Itajuba, MG'},
    {city:'Itambaracá', address:'R. Interventor Manoel Ribas, 180 Centro - Itambaracá, PR'},
    {city:'Itapetininga', address:'R. Dr. Campos Salles, 292 Centro - Itapetininga, SP'},
    {city:'Itapeva', address:'R. Lucas De Camargo, 373Centro - Itapeva, SP'},
    {city:'Itararé', address:'R. Rui Barbosa, 381 Centro - Itararé, SP'},
    {city:'Itobi', address:'R. Inácio Rodrigues Dámaso, 585 Centro - Itobi, SP'},
    {city:'Jacarezinho', address:'R. Parana, 573 Centro - Jacarezinho , PR'},
    {city:'João Pessoa', address:'R. Walfredo Macedo Brandão, 747 Jardim Cidade Universitária - João Pessoa, PB'},
    {city:'Limeira', address:'R. SENADOR VERGUEIRO, 843 CENTRO  - Limeira, SP'},
    {city:'Lucélia', address:'Av. Internacional, 2207 Centro - Lucélia, SP'},
    {city:'Machado', address:'Pç. Antônio Carlos, 50, Loja 05Centro - Machado, MG'},
    {city:'Marília', address:'R. Prudente de Morais, 133 Centro - Marília, SP'},
    {city:'Mococa', address:'R. Gabriel Pinheiro, 1059 Centro - Mococa, SP'},
    {city:'Mogi Guaçu', address:'Av. 9 de Abril, 349 Centro - Mogi Guaçu, SP'},
    {city:'Mogi Mirim', address:'Av. Pedro Botesi, 2800, Loja 32 Parque Novacoop - Mogi Mirim, SP'},
    {city:'Monte Alegre', address:'R. Professor Gaspar, 49 Centro - Monte Alegre, RN'},
    {city:'Monte Belo', address:'R. Cristóvão Colombo, 95 Centro - Monte Belo, MG'},
    {city:'Muzambinho', address:'Av. Dr. Américo Luz, 561 B Centro - Muzambinho, MG'},
    {city:'Natal(Candelária)', address:'Av. Senador José Ferreira de Souza, 1916 Candelária - Natal, RN'},
    {city:'Natal(Satélite)', address:'Av. Xavante, 1094 Loja 04 Cidade Satélite - Natal, RN'},
    {city:'Natal(Zona norte)', address:'R. Ilhéus, 2852 Potengi  - Natal, RN'},
    {city:'Nova Cruz', address:'R. Frei Serafim de Catânia, 646 São Sebastião - Nova Cruz, RN'},
    {city:'Nova Resende', address:'R. Olegário Maciel, 327 Centro - Nova Resende, MG'},
    {city:'Ourinhos', address:'Av. Luis Saldanha Rodrigues, 2751 Vila Santos Dumont - Ourinhos, SP'},
    {city:'Palmital', address:'R. Padre Martins, 162 Centro - Palmital, SP'},
    {city:'Paraguaçu', address:'Pç. Osvaldo Costa, 149 Centro - Paraguaçu, MG'},
    {city:'Parapuã', address:'Av. São Paulo 1045, Quadra 047 Centro - Parapuã, SP'},
    {city:'Parnamirim', address:'R. Sargento Noberto Marques, 148 Centro - Parnamirim, RN'},
    {city:'Pipa', address:'Anel Viário, s/nº, Praia de Pipa Tibau do Sul - Pipa, RN'},
    {city:'Piraju', address:'R. 15 de Novembro, 841, Bloco 1 Centro - Piraju, SP'},
    {city:'Poços de Caldas', address:'R. Santa Catarina, 262Centro - Poços de Caldas, MG'},
    {city:'Porto Seguro', address:'Av. Beira Mar, 367 Centro - Porto Seguro, BA'},
    {city:'Pouso Alegre', address:'R. Dr. Samuel Libânio, 37 Centro - Pouso Alegre, MG'},
    {city:'Presidente Prudente', address:'R. Joaquim Nabuco, 611 Centro - Presidente Prudente, SP'},
    {city:'Ribeirão Claro', address:'R. Dr João Pessoa, 565 Centro - Ribeirão Claro, PR'},
    {city:'Ribeirão do Sul', address:'R. Antônio Luís Viana, 370 Centro  - Ribeirão do Sul, SP'},
    {city:'Ribeirão Claro', address:'R. Dr João Pessoa, 565 Centro - Ribeirão Claro, PR'},
    {city:'Ribeirão do Sul', address:'R. Antônio Luís Viana, 370 Centro  - Ribeirão do Sul, SP'},
    {city:'Rinópolis', address:'R. Prof. Sud Menucci 105 Centro - Rinópolis, SP'},
    {city:'Rio Claro', address:'Av. 10, 256 Centro - Rio Claro, SP'},
    {city:'Salto Grande', address:'R. Rui Barbosa, 836 Centro  - Salto Grande, SP'},
    {city:'Santa Amelia', address:'Av. Carlirio Gomes dos Santos, 466 Centro - Santa Amelia, PR'},
    {city:'Santa Cruz Do Rio Pardo', address:'R. Conselheiro Dantas, 629 Centro - Santa Cruz Do Rio Pardo, SP'},
    {city:'Santa Mariana', address:'Av. Delfim Moreira, 386 Centro - Santa Mariana, PR'},
    {city:'Santa Rita de Caldas', address:'Pç. Dom Otávio, 46 Rio Claro - Santa Rita de Caldas, MG'},
    {city:'Santa Rita do Sapucaí', address:'R. Quintino Bocaiuva, 222 Centro - Santa Rita do Sapucaí, MG'},
    {city:'Santo Antônio', address:'R. Ana Pontes, 362Centro - Santo Antônio, RN'},
    {city:'Santo Antônio da Platina', address:'R. Cel. Joaquim Rodrigues do Prado, 513 Centro - Santo Antônio da Platina, PR'},
    {city:'São João da Boa Vista', address:'Av. Dona Gertrudes, 431 Centro - São João da Boa Vista, SP'},
    {city:'São José de Mipibu', address:'Pref. Juvenal de Carvalho, 40 Centro - São José de Mipibu, RN'},
    {city:'São José do Rio Pardo', address:'R. Francisquinho Dias 725 centro - São José do Rio Pardo, SP'},
    {city:'São Lourenço', address:'R. Antônio Junqueira de Souza, 253 Loja B - São Lourenço, MG'},
    {city:'Serrania', address:'Pç. Minas Gerais, 154 BCentro - Serrania, MG'},
    {city:'Siqueira Campos', address:'R. Rio Grande do Sul, 1573Centro - Siqueira Campos, PR'},
    {city:'Tapiratiba', address:'Pç. Zico Giunti, 696 Centro - Tapiratiba, SP'},
    {city:'Taquarituba', address:'Pç. São Roque, 101 Centro - Taquarituba, SP'},
    {city:'Tatuí', address:'R. 15 de Novembro, 396 Centro - Tatuí, SP'},
    {city:'Três Corações', address:'R. Getúlio Vargas, 54 Centro - Três Corações, MG'},
    {city:'Três Pontas', address:'R. Nossa Sra. D Ajuda, 267 Centro - Três Pontas, MG'},
    {city:'Tupã', address:'R. Potiguaras, 207 Centro - Tupã, SP'},
    {city:'Vargem Grande do Sul', address:'Av. Brasil, 448 Jardim Bela vista - Vargem Grande do Sul, SP'},
    {city:'Varginha', address:'R. Santa Cruz, 550A Centro - Varginha, MG'},
    {city:'Wenceslau Braz', address:'R. Santos Dumont, 168Centro - Wenceslau Braz, PR'}
]